# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 7777

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//cdftest-db.gz.cvte.cn:1521/ptest_newsrm
        username: srm
        password: srm
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        mode: LEGACYHTML5
        cache: false




# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml


